apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-oci-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-oci-binding
subjects:
- kind: ServiceAccount
  name: mcp-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: mcp-oci-role
  apiGroup: rbac.authorization.k8s.io
