apiVersion: 1

datasources:
  - name: Prometheus
    uid: prom
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      # Link exemplars in Prometheus panels to Tempo traces
      exemplarTraceIdDestinations:
        - name: Tempo
          datasourceUid: tempo
        - name: Jaeger
          datasourceUid: jaeger

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      # Show the service map using Prometheus metrics
      serviceMap:
        datasourceUid: prom
      nodeGraph:
        enabled: true
      # Enable trace->metrics linking (uses span attributes to build a PromQL query)
      tracesToMetrics:
        datasourceUid: prom
        # These tags map span attributes to Prometheus labels (adjust to your metrics if needed)
        tags:
          - key: service.name
            value: service_name
          - key: mcp.server.name
            value: mcp_server
          - key: mcp.tool.name
            value: mcp_tool
        spanStartTimeShift: "1h"
        spanEndTimeShift: "1h"
        # Example PromQL for span count/rate (adjust to your metric names as needed)
        query: sum by (service_name) (rate(mcp_tool_duration_seconds_count[5m]))
      # Enable metrics->trace linking from Prometheus panels back to Tempo
      metricsToTraces:
        datasourceUid: prom
        tags:
          - key: service.name
            value: service_name

  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      # Enable trace-to-metrics correlation with Prometheus
      tracesToMetrics:
        datasourceUid: prom
        tags:
          - key: service_name
            value: service.name
          - key: mcp_server
            value: mcp.server.name
          - key: mcp_tool
            value: mcp.tool.name
        spanStartTimeShift: "1h"
        spanEndTimeShift: "1h"
        # Example PromQL for MCP metrics
        query: sum by (mcp_server, mcp_tool) (rate(mcp_tool_calls_total[5m]))
      # Enable trace-to-logs correlation
      tracesToLogs:
        datasourceUid: prom
        tags:
          - service_name
          - traceID
    basicAuth: false
    isDefault: false

  - name: grafana-pyroscope-datasource
    uid: cezjqpbqlfwn4e
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      timeout: 30
      # Enable profiling-to-tracing correlation
      tracesToProfiles:
        datasourceUid: tempo
        tags:
          - service_name
          - pyroscope_profile_id
    basicAuth: false
    isDefault: false
